namespace Rhyme.Common
{
	public static class Protocols
	{
		//------------------------------------------------------------------------------
		// <auto-generated>
		//     This code was generated by a tool.
		//     TagVersion : 1.2.10
		public const string ProtocolVersion = "09289c7b-5e8f-3b98-e713-b54b0e0840f1";
		//     Changes to this file may cause incorrect behavior and will be lost if
		//     the code is regenerated.
		// </auto-generated>
		//------------------------------------------------------------------------------
	}
}
