using ProtoBuf;

namespace Rhyme.Common
{
	[ProtoContract(ImplicitFields = ImplicitFields.AllPublic)]
	public enum ResultCode
	{
		Success = 0,

		///////////////////////////////////// General error code 0-1000 /////////////////////////////////////
		//ErrorNotImplemented = 1,
		//InvalidCurrency = 2,
		ErrorBadRequest = 3,
		ErrorDeprecated = 4,
		ErrorNotFound = 5,
		ErrorDenied = 6,
		//ErrorUnhandledException = 7,
		ErrorInvalidProtocolVersion = 8,
		ErrorChannelNotFound = 9,
		ErrorInternal = 10,
		ErrorShuttingDown = 11,
		ErrorInvalidArgument = 12,
		//ErrorDbMaintenance = 13,
		ErrorNotReady = 14,
		ErrorUnableToConnectSessionService = 15,
		ErrorAlreadyExists = 16,
		ErrorExpired = 17,
		ErrorNotSupported = 18,
		ErrorBlockCountryCode = 19,
		ErrorFindPlayerNotFound = 20,
		ErrorTableTerminated = 21,
		ErrorUnknownIPAddress = 22,
		ErrorServerBusy = 23,
		ErrorInvalidRequestId = 24,
		ErrorTimeOut = 25,
		ErrorMessageTooLong = 26,
		ErrorLabelNotFound = 27,
		ErrorInvalidCurrencyValue = 28,
		ErrorCurrencyNotFound = 29,
		ErrorNotProcessed = 30,

		///////////////////////////////////// Account Service 1001-2000 /////////////////////////////////////
		ErrorAccountNotFound = 1001,
		//ErrorAccountAlreadyExists = 1002,
		//ErrorAccountAlreadyLogin = 1003,
		ErrorAccountDuplicateLogin = 1004,
		ErrorAccountNotLoggedIn = 1005,
		//ErrorAccountPasswordNotMatched = 1006,
		ErrorAccountSpNotFound = 1007,
		//ErrorAccountMailNotFound = 1008,
		ErrorInsufficientFunds = 1009,
		//ErrorDupTransactionId = 1010,
		ErrorBuyInFailed = 1011,
		ErrorCashOutFailed = 1012,
		ErrorAlreadyCompleted = 1013,
		ErrorAccountInviteeNotFound = 1014,
		ErrorAccountWhisperNotFoundReceiver = 1015,
		ErrorGetBalanceFailed = 1016,
		ErrorRebuyInProcess = 1017,
		ErrorBuyInCanceled = 1018,
		ErrorCashOutPending = 1019,
		ErrorCancelPending = 1020,
		//ErrorSaveGGPointFailed = 1021,
		//ErrorGetUserRankInfoFailed = 1022,
		//ErrorNotImplementedRankValue = 1023,
		ErrorAccountWhisperDenied = 1024,
		//ErrorAccountMailDenied = 1025,
		ErrorAccountUnknownPlatform = 1026,
		ErrorAccountAuthFailed = 1027,
		ErrorPlatformCreateTokenFailed = 1028,
		ErrorServiceProviderNotFound = 1029,
		ErrorServiceProviderMismatch = 1030,
		ErrorNameNotExists = 1031,
		ErrorNameTooLong = 1033,
		ErrorNameTooShort = 1034,
		ErrorNameAlreadyUsed = 1035,
		ErrorPlatformSetNameFailed = 1036,
		ErrorNameNotAllowed = 1037,
		ErrorDeductionPending = 1038,
		ErrorAccountInviteDenied = 1039,
		ErrorAccountLocked = 1040,
		ErrorGGPointConversionInvalid = 1041,
		//ErrorGGPointMarketItemNotFound = 1042,
		//ErrorGGPointMarketPurchaseNotAllowed = 1043,
		//ErrorInsufficientGGPoint = 1044,
		ErrorImageLocked = 1045,
		//ErrorNotDomestic = 1046,
		//ErrorNotAllowTransfer = 1047,
		ErrorAccountBuddyDenied = 1048,
		ErrorAccountBuddyPending = 1049,
		//ErrorUpdateGGPGainRatioFailed = 1050,
		//ErrorGGPointMarketItemCategoryNotFound = 1051,
		ErrorUpdateAvatarIdFailed = 1052,
		ErrorNameStartWithSpace = 1053,
		ErrorCashOutInProcess = 1054,
		ErrorNotAllowedIP = 1055,
		ErrorNotAllowedChangeNickName = 1056,
		ErrorAccountAccessDenied = 1057,
		ErrorBuyInProcess = 1058,
		ErrorGetJackpotHandHistoryFailed = 1059,
		ErrorNotAllowedBuddy = 1060,
		ErrorDuplicateMachineLogin = 1061,
		ErrorPlatformAddSpecialAvatar = 1062,
		ErrorPlatformGetSpecialAvatar = 1063,
		ErrorPlatformGetDefaultAvatar = 1064,
		ErrorSetAvatarFailed = 1070,
		ErrorDeductFailed = 1071,

		///////////////////////////////////// Table Service 2001- 3000 /////////////////////////////////////
		ErrorTableNotFound = 2001,
		ErrorStakeNotFound = 2002,
		ErrorInvalidSeatIndex = 2003,
		ErrorSeatAlreadyTaken = 2004,
		ErrorTablePlayerNotFound = 2005,
		ErrorTablePlayerSeatNotTaken = 2006,
		ErrorLessThanMinBuyIn = 2007,
		ErrorMoreThanMaxBuyIn = 2008,
		ErrorBadPlayerStatus = 2009,
		ErrorDuplicatePlayer = 2010,
		ErrorReservedSeatNotReserved = 2011,
		ErrorReservedSeatNotOwnedByPlayer = 2012,
		ErrorNotInWaitingList = 2013,
		ErrorAlreadyInWaitingList = 2014,
		ErrorAlreadyEntered = 2015,
		ErrorAlreadyReserved = 2016,
		ErrorUnableToCreateMorePrivateTable = 2017,
		ErrorUnableToConnectTableService = 2018,
		ErrorSecurityNegotiationFailed = 2019,
		ErrorWaitingListFull = 2020,
		ErrorPlayingGame = 2021,
		ErrorLessThanLastSaveBalance = 2022,
		ErrorLeaveSeatNotAllowed = 2023,
		ErrorSitOutNotAllowed = 2024,
		ErrorSitInNotAllowed = 2025,
		ErrorSameAddressNotAllowed = 2026,
		ErrorBuyInChangeNotAllowedAtTourney = 2027,
		ErrorReEntryFrequencyLimit = 2028,
		ErrorCashOutNotAllowedAtTourney = 2029,
		ErrorTooManyBubbleMessage = 2030,
		ErrorClientCannotReserveSeat = 2031,
		ErrorAutoJoinFailed = 2032,
		ErrorSeatNotAvailable = 2033,
		ErrorHoleCardNotFound = 2034,
		ErrorEnterTableNotPossible = 2035,
		ErrorInvalidJoinCashGameArgument = 2036,
		ErrorInvalidJoinGameEntryCount = 2037,
		ErrorJoinGameEntryCountLessThanMin = 2038,
		ErrorJoinGameEntryCountMoreThanMax = 2039,
		ErrorTableNotFoundForJoinCashGame = 2040,

		///////////////////////////////////// Game service 3001-4000 /////////////////////////////////////
		//ErrorButtonMoveFailed = 3001,
		ErrorNotEnoughBalance = 3002,
		ErrorActionNotAllowed = 3003,
		//ErrorBadActionAmount = 3004,
		ErrorGameNotFound = 3005,
		ErrorActionNotFound = 3006,
		ErrorBadActionType = 3007,

		// on action raise
		ErrorBadActionAmountBalanceLessThenBetAmount = 3008,
		ErrorBadActionAmountBetAmountTooSmall = 3009,
		ErrorBadActionAmountRaiseLessThanComittedAmount = 3010,
		ErrorBadActionAmountBalanceLessThanRaiseAmount = 3011,
		ErrorBadActionAmountActualRaiseAmountLessThanCallAmount = 3012,
		ErrorBadActionAmountBalanceLessThanLastBetAmountOrMinBet = 3013,
		ErrorBadActionAmountNotEnoughBalanceLessThanRaiseAmount = 3014,

		///////////////////////////////////// Game service 4001-5000 /////////////////////////////////////
		ErrorInvalidToken = 4001,

		///////////////////////////////////// Jump Service 5001-6000 /////////////////////////////////////
		ErrorJumpTooManyEntries = 5001,
		ErrorJumpEntryNotFound = 5002,
		ErrorJumpFindEntryByUserNotFound = 5003,
		ErrorJumpFindUserEntryNotFound = 5004,
		ErrorJumpAlreadyAddedSubscriber = 5005,
		ErrorJumpRegistSubscriberFailed = 5006,
		ErrorJumpUnRegistSubscriberFailed = 5007,
		ErrorJumpChangeUserStateFailed = 5008,
		ErrorJumpGetTableInformationFailed = 5009,
		ErrorJumpGetUserEntriesFailed = 5010,
		ErrorJumpAddUserEntryFailed = 5011,
		ErrorJumpTableNotFound = 5012,
		ErrorJumpNotEnoughBalance = 5013,

		///////////////////////////////////// Tourney Service 6001-7000/////////////////////////////////////
		ErrorTourneyUserAlreadyRegistered = 6001,
		ErrorTourneyUserNotRegistered = 6002,
		//ErrorTourneyUserAlreadySubscribed = 6003,
		//ErrorTourneyUserNotSubscribed = 6004,
		ErrorTourneyRegisterNotAllowed = 6005,
		ErrorTourneyUnregisterNotAllowed = 6006,
		ErrorTourneyNotFound = 6007,
		ErrorTourneyTableNotFound = 6008,
		ErrorTourneyRegisterMaxPlayersExceeded = 6009,
		ErrorTourneyPlayerAlreadyAddedOn = 6010,
		//ErrorTourneyPlayerNotOnBreak = 6011,
		ErrorTourneyPlayerNoRemainingRebuy = 6012,
		ErrorTourneyIsNotAddonPeriod = 6013,
		ErrorTourneyTooManyChipsRebuyNotAllowed = 6014,
		ErrorTourneyAlreadyExistingPendingRebuy = 6015,
		ErrorTourneyTicketNotFound = 6016,
		ErrorTourneyInvalidUserRank = 6017,
		ErrorTourneyInvalidServiceProvider = 6018,
		//ErrorTourneyMoneyInsufficient = 6019,
		//ErrorTourneyTicketAlreadyUsedOrExpired = 6020,
		//ErrorTourneyTicketNotUsed = 6021,
		//ErrorTourneyFailedToCancelTicketUse = 6022,
		ErrorTourneyAlreadyCreated = 6023,
		//ErrorTourneyMustUseTicket = 6024,
		ErrorTourneyTicketDiscountTimeOver = 6025,
		ErrorTourneyTicketAlreadyDiscountPurchase = 6026,
		ErrorTourneyIsNotProgressive = 6027,
		ErrorTourneyAlreadyInTheMoney = 6028,
		ErrorTourneyAddOnNotAllowed = 6029,
		ErrorTourneyIsNotRebuyPeriod = 6030,
		ErrorTourneyMegaSpinRegisterMaxExceeded = 6031,
		ErrorStopMegaSpinRegistration = 6032,
		ErrorTourneyNotAllowedBuyinType = 6033,
		//ErrorTourneyTicketCreate = 6034,
		//ErrorTourneyAddOnFailed = 6035,
		ErrorTourneyPlayerInsert = 6036,
		ErrorTourneyRegistrationInsert = 6037,
		ErrorTourneyHasOtherImmigrationPlan = 6038,
		ErrorTourneyNotRunning = 6039,

		///////////////////////////////////// DB Service 7001-8000 /////////////////////////////////////
		ErrorDbTransactionAlreadyExists = 7001,
		ErrorNotEnoughGGPoint = 7002,
		ErrorInvalidParmeter = 7003,
		ErrorBuddyAlreadyExists = 7004,
		ErrorUserOptionChanged = 7005,
		//ErrorNotEnoughJackpotAmount = 7006,

		///////////////////////////////////// Lobby Service 8001-8100 /////////////////////////////////////
		ErrorLobbyNotExistsLobby = 8001,
		//ErrorLobbyAlreadyEnterGameLobby = 8002,
		ErrorLobbyNotExistsGameLobby = 8003,

		///////////////////////////////////// Table Manager /////////////////////////////////////
		ErrorMaxOpenTableExceeded = 9001,
		ErrorTableTypeNotFound = 9002,

		///////////////////////////////////// Proxy /////////////////////////////////////
		ErrorNotFoundProxyProtocol = 10001,
		ErrorDispatchExceptionOccured = 10002,
		ErrorLowVersionMajor = 10003, // version
		ErrorLowVersionMinor = 10004, // version
		ErrorLowVersionPatch = 10005, // version
		ErrorProtocolNotMatched = 10006,
		ErrorServiceChannelNotFound = 10007,
		ErrorCallbackServiceChannelNotFound = 10008,
		ErrorPacketBodyIsNull = 10009,
		ErrorSerialize = 10010,
		ErrorDispatchProtocol = 10011,
		ErrorDispatchProtocolSetResponse = 10012,
		ErrorResponsePacketIsNull = 10013,			// for Invoke<TRequest, TResponse>
		ErrorResponseCastingFailed = 10014,			// for Invoke<TRequest, TResponse>
		ErrorResponseTaskCanceled = 10015,			// for Invoke<TRequest, TResponse>
		ErrorDispatchProtocolUnobservedTaskException = 10016,

		///////////////////////////////////// 2Ace. 20001 ~ 29999 /////////////////////////////////////

		// Chip Dumping Table
		ErrorTablePasswordNotCorrect = 20001,
		ErrorEmptyDumpTableNotExist = 20002,
		ErrorDumpTableLessThanMinBuyIn = 20003,
		ErrorDumpTableMoreThanMaxBuyIn = 20004,
		ErrorDumpTableInvalidDumpBuyInType = 20005,
		ErrorDumpTableInvalidPassword = 20006,			// invalid password
		ErrorDumpTablePasswordNotNumeric = 20007,			// invalid password
		ErrorDumpTablePasswordTooShort = 20008,			// invalid password
		ErrorDumpTablePasswordTooLong = 20009,			// invalid password
		ErrorDumpTableInvalidDecryptedPassword = 20010,	// invalid password
		ErrorDumpTableAccessOnlyPersonalMerchant = 20011,
		ErrorDumpTableException = 20012,

		// Player Level and Exp
		ErrorDbUpdatePlayerLevel = 21000,
		ErrorDbUpdatePlayerExp = 21001,
		UpdatePlayerExpIgnore = 21002,		// not error
		UpdatePlayerExpLevelUp = 21003,		// not error
		ErrorUpdatePlayerExpNoCacheData = 21004,
		ErrorUpdatePlayerExpException = 21005,
		ErrorPrepareLevelUpReward = 21006,
		ErrorPlatformRewardFailed = 21007,

		// Item Inventory
		ErrorDbUpdateItemOptionNoItem = 22000,
		ErrorUseItemException = 22001,
		ErrorInvalidItemId = 22002,
		ErrorDoNotHaveItem = 22003,
		ErrorNotEnoughItemStock = 22004,
		ErrorBuyItemAlreadyExist = 22005,
		ErrorBuyItemException = 22006,
		ErrorBuyItemPlatform = 22007,
		ErrorChangeAvatarPlatform = 22008,
		ErrorBuyItemAccessDenied = 22009,

		// Item : Expendable - Mega phone
		ErrorGetMegaPhoneUseHistoryExceptionAtClientChannel = 22101,
		ErrorGetMegaPhoneUseHistoryExceptionAtClientChannelInner = 22102,
		ErrorGetMegaPhoneUseHistoryExceptionAtAccountChannel = 22103,
		ErrorGetMegaPhoneUseHistoryExceptionAtAccountChannelInner = 22104,
		ErrorUseItemMegaPhoneException = 22105,
		ErrorUseItemMegaPhoneMessageTooShort = 22106,
		ErrorUseItemMegaPhoneMessageTooLong = 22107,
		ErrorUseItemMegaPhone = 22108,
		ErrorUseItemMegaPhoneCreateHistory = 22109,
		ErrorUseItemMegaPhoneDbupdate = 22110,
		ErrorExpendableItemNotUsed = 22111,

		ErrorResultMax = int.MaxValue
	}
}